# Generated by Django 4.1.4 on 2023-01-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('my_tag', models.CharField(default='', max_length=7)),
                ('friend_tag', models.CharField(default='', max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='invites',
            fields=[
                ('invite_id', models.CharField(default='aabb11', max_length=8, primary_key=True, serialize=False)),
                ('sent_to', models.CharField(max_length=7)),
                ('from_user', models.CharField(max_length=7)),
                ('invite_status', models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('D', 'DECLINED')], default=('P', 'PENDING'), max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('targeted_user', models.CharField(default='aabb11', max_length=7, primary_key=True, serialize=False)),
                ('message', models.CharField(default='notification', max_length=100)),
                ('received', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('usertag', models.CharField(default='aabb11', max_length=7)),
                ('level', models.IntegerField(default=1)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
