# Generated by Django 4.1.4 on 2022-12-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_level_user_user_tag_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_tag',
        ),
        migrations.AddField(
            model_name='user',
            name='usertag',
            field=models.CharField(default=' ', max_length=6),
        ),
    ]
