# Generated by Django 4.1.4 on 2022-12-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_user_tag_user_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_invites',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_invites',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertag',
            field=models.CharField(default='no tags inputed!', max_length=6),
        ),
    ]
