# Generated by Django 4.1.4 on 2022-12-29 21:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_user_tag_user_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='$%$%$%', max_length=7), default=' ', size=None),
        ),
    ]
