# Generated by Django 4.1.4 on 2022-12-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_invites_alter_user_usertag'),
        ('user', '0005_user_accepted_invites_user_pending_invites_and_more'),
    ]

    operations = [
    ]
