# Generated by Django 4.1.4 on 2022-12-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_accepted_invites_user_pending_invites_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_invites', models.JSONField(default=list)),
                ('accepted_invites', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='accepted_invites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pending_invites',
        ),
        migrations.AlterField(
            model_name='user',
            name='usertag',
            field=models.CharField(default='no tags inputed!', max_length=7),
        ),
    ]
