# Generated by Django 4.1.4 on 2022-12-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_invites',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_invites',
            field=models.JSONField(default=list),
        ),
    ]
