# Generated by Django 4.1.4 on 2022-12-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_invites_alter_user_usertag'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(max_length=7)),
                ('invite_status', models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('D', 'DECLINED')], default=('P', 'PENDING'), max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Invites',
        ),
    ]
