# Generated by Django 4.1.4 on 2022-12-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_sentinvites_delete_invites'),
    ]

    operations = [
        migrations.CreateModel(
            name='receivedInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=7)),
                ('invite_status', models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('D', 'DECLINED')], default=('P', 'PENDING'), max_length=9)),
            ],
        ),
    ]
