# Generated by Django 4.1.4 on 2023-01-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_receivedinvites'),
    ]

    operations = [
        migrations.CreateModel(
            name='invites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(editable=False, max_length=7)),
                ('from_user', models.CharField(editable=False, max_length=7)),
                ('invite_status', models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('D', 'DECLINED')], default=('P', 'PENDING'), max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='receivedInvites',
        ),
        migrations.DeleteModel(
            name='sentInvites',
        ),
    ]
