# Generated by Django 4.1.4 on 2023-01-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_invites_delete_receivedinvites_delete_sentinvites'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_tag', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='invites',
            name='from_user',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='invites',
            name='sent_to',
            field=models.CharField(max_length=7),
        ),
    ]
