# Generated by Django 4.1.4 on 2023-01-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_friend_alter_invites_from_user_alter_invites_sent_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='id',
        ),
        migrations.AddField(
            model_name='invites',
            name='invite_id',
            field=models.CharField(default='aabb11', max_length=8),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend_tag',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
