# Generated by Django 4.1.4 on 2023-01-03 00:29

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_friend_id_invites_invite_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invites',
            name='id',
        ),
        migrations.AddField(
            model_name='friend',
            name='fk',
            field=models.ForeignKey(default=user.models.User, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='invites',
            name='invite_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
