# Generated by Django 4.1.4 on 2023-01-03 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_invites_id_friend_fk_alter_invites_invite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertag',
            field=models.CharField(default='aabb11', max_length=7),
        ),
    ]
