# Generated by Django 4.1.4 on 2023-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_friend_fk_alter_user_usertag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='fk',
        ),
        migrations.AddField(
            model_name='friend',
            name='my_tag',
            field=models.CharField(default='aabb11', max_length=7),
        ),
    ]
