# Generated by Django 4.1.4 on 2023-01-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_friend_fk_friend_my_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targeted_user', models.CharField(default='aabb11', max_length=7)),
                ('message', models.CharField(default='notification', max_length=100)),
            ],
        ),
    ]
