# Generated by Django 4.0 on 2023-02-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.ManyToManyField(related_name='notification', to='user.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
