# Generated by Django 4.0 on 2023-03-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_notification_delete_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.CharField(default='aabb69', max_length=10),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_to',
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_to',
            field=models.JSONField(default=list),
        ),
    ]
