# Generated by Django 4.0 on 2023-05-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(max_length=700),
        ),
    ]
