# Generated by Django 4.0 on 2023-04-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Um_Compete',
            fields=[
                ('um_compete_challenge_id', models.CharField(default='aabbccddee', max_length=10, primary_key=True, serialize=False)),
                ('um_compete_challenge_subject', models.CharField(choices=[('Mathematics', 'M'), ('History', 'H'), ('Ethics', 'E'), ('Science', 'S'), ('Geography', 'G'), ('Languages', 'L'), ('Art', 'A'), ('Communication/personal_help', 'C'), ('Fun', 'F')], default='Fun', max_length=40)),
                ('host_username', models.CharField(default='aabb11', max_length=7)),
                ('team_1', models.JSONField(default=list)),
                ('team_2', models.JSONField(default=list)),
                ('sent_to', models.JSONField(default=list)),
                ('accepted_members', models.JSONField(default=list)),
                ('title', models.CharField(default='Um Compete Title!', max_length=30)),
                ('description', models.TextField(max_length=275)),
                ('questions', models.JSONField(default=list)),
                ('hasStarted', models.BooleanField(default=False)),
                ('team_1_score', models.IntegerField(default=0, null=True)),
                ('team_2_score', models.IntegerField(default=0, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('gamify', models.BooleanField(default=False)),
            ],
        ),
    ]
