# Generated by Django 4.1.4 on 2023-01-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('um_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='um_compete',
            name='play_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
