# Generated by Django 4.0 on 2023-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('um_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='um_compete',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
