# Generated by Django 4.1.4 on 2023-01-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('um_challenge', '0002_alter_um_compete_play_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='um_compete',
            name='play_date',
        ),
    ]
