# Generated by Django 4.1.4 on 2023-02-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('um_challenge', '0004_um_compete_hasstarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='um_compete',
            name='team_1_score',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='um_compete',
            name='team_2_score',
            field=models.JSONField(default=list),
        ),
    ]
