# Generated by Django 4.1.4 on 2023-02-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('um_challenge', '0005_um_compete_team_1_score_um_compete_team_2_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='um_compete',
            name='team_1_score',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='um_compete',
            name='team_2_score',
            field=models.JSONField(default=[]),
        ),
    ]
