# Generated by Django 4.1.4 on 2023-02-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('um_challenge', '0006_alter_um_compete_team_1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='um_compete',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
