# Generated by Django 4.1.4 on 2023-01-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpzone', '0003_rename_answerer_id_answer_answer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asker_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='time_published',
            field=models.DateField(auto_now=True),
        ),
    ]
