# Generated by Django 4.0 on 2023-02-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpzone', '0005_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
