# Generated by Django 4.0 on 2023-06-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpzone', '0010_question_vote_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
    ]
