# Generated by Django 4.1.4 on 2023-01-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrt_trm_ch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentshrttrmch',
            name='score',
            field=models.JSONField(blank=True, default=dict, null=True, unique=True),
        ),
    ]
