# Generated by Django 4.1.4 on 2023-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrt_trm_ch', '0003_sentshrttrmch_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentshrttrmch',
            name='scores',
            field=models.JSONField(default=list),
        ),
    ]
