# Generated by Django 4.0 on 2023-03-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrt_trm_ch', '0005_sentshrttrmch_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedshrttrmch',
            name='study',
            field=models.BooleanField(default=False),
        ),
    ]
