# Generated by Django 4.0 on 2023-04-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrt_trm_ch', '0006_receivedshrttrmch_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedshrttrmch',
            name='study',
        ),
        migrations.AddField(
            model_name='sentshrttrmch',
            name='study',
            field=models.BooleanField(default=False),
        ),
    ]
