# Generated by Django 4.0 on 2023-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrt_trm_ch', '0007_remove_receivedshrttrmch_study_sentshrttrmch_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentshrttrmch',
            name='mastered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentshrttrmch',
            name='user_mastered_count',
            field=models.JSONField(default={}),
        ),
    ]
