# Generated by Django 4.0 on 2023-04-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrt_trm_ch', '0008_sentshrttrmch_mastered_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentshrttrmch',
            old_name='user_mastered_count',
            new_name='mastered',
        ),
    ]
