# Generated by Django 4.0 on 2023-04-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrt_trm_ch', '0010_alter_sentshrttrmch_mastered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentshrttrmch',
            name='mastered',
            field=models.JSONField(default=[]),
        ),
    ]
