# Generated by Django 4.0 on 2023-04-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrt_trm_ch', '0013_remove_sentshrttrmch_mastered'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentshrttrmch',
            name='mastered',
            field=models.JSONField(default=list),
        ),
    ]
